# This is a basic workflow to help you get started with Actions

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Copy files to EC2 server
        run: |
          scp -r build/* username@ec2-ip-address:/path/to/destination

  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS Lambda
        run: |
         serverless deploy

     
